# Generated by Django 5.2.8 on 2025-11-17 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Sesión')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total de Ítems')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('reason', models.CharField(choices=[('order', 'Orden Creada'), ('manual', 'Guardado Manual'), ('abandoned', 'Carrito Abandonado')], default='manual', max_length=50, verbose_name='Razón')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_histories', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Carrito',
                'verbose_name_plural': 'Historiales de Carritos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('cart_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.carthistory', verbose_name='Historial')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem del Historial',
                'verbose_name_plural': 'Ítems del Historial',
                'ordering': ['id'],
            },
        ),
    ]
